import { useUnit } from "effector-react";
import {
  formAmountChange,
  formDescriptionChange,
  transactionCreatedFailure,
  transactionCreatedSuccess,
  formPhotoUrlChange,
  $transactionForm,
  pageChange,
  $transactions,
  allTransactionReq,
  $sort,
  limitChange,
  sortByChange,
  $isModalOpen,
  modalOpenEvent,
  countTransactionsChangeEvent,
  $countTransactions,
} from "../../model/store";

export const useTransaction = () => {
  const {
    createdEventSuccess,
    createdEventFailure,
    setPage,
    transactions,
    AmountChange,
    DescriptionChange,
    onLimitChange,
    onPageChange,
    isModalOpen,
    openModal,
    onSortByChange,
    count,
    countTransactionsChange,
    getAllTransactions,
    PhotoChange,
    sortOptions,
    form,
  } = useUnit({
    createdEventSuccess: transactionCreatedSuccess,
    createdEventFailure: transactionCreatedFailure,
    setPage: pageChange,
    onLimitChange: limitChange,
    onPageChange: pageChange,
    onSortByChange: sortByChange,
    getAllTransactions: allTransactionReq,
    transactions: $transactions,
    isModalOpen: $isModalOpen,
    count: $countTransactions,
    countTransactionsChange: countTransactionsChangeEvent,
    openModal: modalOpenEvent,
    AmountChange: formAmountChange,
    DescriptionChange: formDescriptionChange,
    PhotoChange: formPhotoUrlChange,
    form: $transactionForm,
    sortOptions: $sort,
  });

  return {
    createdEventSuccess,
    createdEventFailure,
    count,
    countTransactionsChange,
    AmountChange,
    transactions,
    getAllTransactions,
    DescriptionChange,
    setPage,
    isModalOpen,
    openModal,
    onLimitChange,
    onPageChange,
    onSortByChange,
    form,
    sortOptions,
    PhotoChange,
  };
};
