FROM node:20-alpine

WORKDIR /app

# Use package-lock.json if available for more consistent installs
COPY package*.json ./

# Install all dependencies (including devDependencies)
RUN npm install

COPY . .

EXPOSE 3000

# Set development environment
ENV NODE_ENV=development \
    CHOKIDAR_USEPOLLING=true


CMD ["npm", "run", "start:dev"]